name: Main workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container: gradle:6jdk11

    steps:
      - name: Clone down repository
        uses: actions/checkout@v4
      - name: Build application
        run: ci/build-app.sh
